<?php
require("../class/connect.php");
require("../class/q_functions.php");
require("../member/class/user.php");
require("../data/dbcache/MemberLevel.php");
eCheckCloseMods('pay');//关闭模块
$link=db_connect();
$empire=new mysqlquery();
//是否登录
$user=islogin();
//支付平台
$payid=intval($_POST['payid']);
if(!$payid)
{
	printerror('请选择支付平台','',1,0,1);
}
//充值类型
$id=intval($_POST['id']);
if(!$id)
{
	printerror('请选择充值类型','',1,0,1);
}
$payr=$empire->fetch1("select * from {$dbtbpre}enewspayapi where payid='$payid' and isclose=0".do_dblimit_one());
if(!$payr['payid'])
{
	printerror('请选择支付平台','',1,0,1);
}
$buyr=$empire->fetch1("select * from {$dbtbpre}enewsbuygroup where id='$id'");
if(!$buyr['id'])
{
	printerror('请选择充值类型','',1,0,1);
}
//权限
if($buyr['buygroupid']&&$level_r[$buyr['buygroupid']]['level']>$level_r[$user['groupid']]['level'])
{
	printerror('此充值类型需要 '.$level_r[$buyr['buygroupid']]['groupname'].' 会员级别以上','',1,0,1);
}
//有效期验证
if($buyr['gdate']&&$user['groupid']!=$buyr['ggroupid'])
{
	if($user['userdate']&&$user['userdate']>=time())
	{
		if(!$public_r['mhavedatedo'])
		{
			printerror('您当前的会员组有效期未到，不能充值新会员组','',1,0,1);
		}
	}
}
$ddno='';
$productname='';
$productsay='';

include('payfun.php');

$money=$buyr['gmoney'];
$money=efmmoney($money);
if($money<=0)
{
	printerror('此充值类型金额有误','',1,0,1);
}
//支付参数
$prdr=array();
$prdr['userid']=$user['userid'];
$prdr['username']=$user['username'];
$prdr['orderid']='';
$prdr['money']=$money;
$prdr['posttime']='';
$prdr['paybz']='';
$prdr['paytype']=$payr['paytype'];
$prdr['payip']='';
$prdr['ispay']=0;
$prdr['paydo']='BuyGroupPay';
$prdr['payfor']=$buyr['id'];
$prdr['payckcode']='';
$prdr['payddno']=epayapi_ReturnDdno($prdr['userid']);
$prdr['endtime']='';
//支付参数
$ddno='';
$prdr['pname']="充值类型:".$buyr['gname'].",UID:".$user['userid'].",UName:".$user['username'];
$prdr['psay']="充值类型:".$buyr['gname'].",用户ID:".$user['userid'].",用户名:".$user['username'];
$ddno=$prdr['payddno'];
$productname=$prdr['pname'];
$productsay=$prdr['psay'];

esetcookie("payphome","BuyGroupPay",0);
esetcookie("paymoneybgid",$id,0);
//返回地址前缀
$PayReturnUrlQz=$public_r['newsurl'];
if(!stristr($public_r['newsurl'],'://'))
{
	$PayReturnUrlQz=eReturnDomain().$public_r['newsurl'];
}
//编码
$iconv='';
$char='';
$targetchar='';
/*
if($ecms_config['sets']['pagechar']!='gb2312')
{
	$char=$ecms_config['sets']['pagechar']=='big5'?'BIG5':'UTF8';
	$targetchar='GB2312';
	$productname=DoIconvVal($char,$targetchar,$productname);
	$productsay=DoIconvVal($char,$targetchar,$productsay);
	@header('Content-Type: text/html; charset=gb2312');
}
*/
//记录
$re_prdr=epayapi_AddPayRecord($prdr);
$prdr['id']=$re_prdr['id'];
$prdr['payckcode']=$re_prdr['payckcode'];
$prdr['posttime']=$re_prdr['posttime'];
$prdr['payip']=$re_prdr['payip'];

eCheckStrType(4,$payr['paytype'],1);
$file=$payr['paytype'].'/to_pay.php';
@include($file);
db_close();
$empire=null;
?>