<?php
exit();
define('EmpireCMSAdmin','1');
require("../../../e/class/connect.php");
require("../../../e/class/functions.php");
$link=db_connect();
$empire=new mysqlquery();
$editor=1;
//验证用户
$lur=is_login();
$logininid=(int)$lur['userid'];
$loginin=$lur['username'];
$loginrnd=$lur['rnd'];
$loginlevel=(int)$lur['groupid'];
$loginadminstyleid=(int)$lur['adminstyleid'];
//ehash
$ecms_hashur=hReturnEcmsHashStrAll();
hCheckEcmsRHash();
//初使化
$from=RepPostStrUrl($_GET['from']);
if($_GET['first']==1)
{
	$rechecktablenum=0;
}
else
{
	$rechecktablenum=$_COOKIE['rechecktablenum'];
	$rechecktablenum+=1;
}
if($rechecktablenum>=$_COOKIE['retablenum'])
{
	$enews="ReNewsHtml";
	//操作日志
	insert_dolog("");
	echo"<script>alert('刷新信息页面成功!');parent.location.href='$from';</script>";
}
else
{
	//setcookie("rechecktablenum",$rechecktablenum,0,"/","");
}
db_close();
$empire=null;
?>